# Generated by Django 5.2.17 on 2026-08-31 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('icon', models.CharField(default='bi-tags', help_text='Bootstrap Icon class, e.g. bi-film', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FrameOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('frame_type', models.CharField(choices=[('none', 'No Frame / Rolled Canvas'), ('black', 'Matte Black Wooden Frame'), ('white', 'Minimalist White Frame'), ('wooden', 'Natural Walnut Wooden Frame')], default='none', max_length=20)),
                ('extra_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('color_code', models.CharField(default='#1E1E1E', help_text='Hex color code for frame border preview', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='frames/')),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'extra_price'],
            },
        ),
        migrations.CreateModel(
            name='PosterSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. A4 (8.3 x 11.7 in)', max_length=50)),
                ('code', models.CharField(help_text='e.g. A4, A3, A2', max_length=10, unique=True)),
                ('extra_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Extra cost for this size', max_digits=8)),
                ('dimensions', models.CharField(blank=True, help_text='e.g. 21.0 x 29.7 cm', max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'extra_price'],
            },
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('description', models.TextField()),
                ('main_image', models.ImageField(upload_to='posters/')),
                ('base_price', models.DecimalField(decimal_places=2, default=299.0, max_digits=8)),
                ('stock', models.PositiveIntegerField(default=100)),
                ('rating', models.DecimalField(decimal_places=1, default=4.8, max_digits=3)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated keywords for search', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posters', to='store.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PosterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posters/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='store.poster')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(5, '★★★★★ - Excellent'), (4, '★★★★☆ - Very Good'), (3, '★★★☆☆ - Good'), (2, '★★☆☆☆ - Fair'), (1, '★☆☆☆☆ - Poor')], default=5)),
                ('review_text', models.TextField()),
                ('is_verified_purchase', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.poster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
