# Generated by Django 5.2.17 on 2026-09-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='source_filename',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
