# Generated by Django 5.2.17 on 2026-09-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_poster_source_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
