# Generated by Django 5.2.17 on 2026-08-31 14:32

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('uploaded_image', models.ImageField(upload_to='custom_posters/')),
                ('custom_text', models.CharField(blank=True, help_text='Optional custom quote or title on poster', max_length=255)),
                ('special_instructions', models.TextField(blank=True, help_text='Any cropping or styling preferences')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('349.00'), max_digits=8)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('349.00'), max_digits=8)),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('349.00'), max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('frame', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.frameoption')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.postersize')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_posters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
